### ISSUE TITLE
Updating the extension overwrites custom presets

### ISSUE THREAD

**Issue by hzielke** [Gerschel/sd_web_ui_preset_utils#23]
Could you provide way to retain saved presets (even if not in working order) when updating/overwriting the extension? Perhaps a diffent filename for the provided examples?

**Comment by Gerschel** [comment]
I was wondering how this was going to go down. I've noticed this happen with other projects. I think it's because the web-ui is set to reclone the repository, so even if I don't push a change, it grabs it fresh.  
I have an idea of how to workaround this, a couple of them, I toyed around and had made an update script for this situation just in case, I'll have to bring up to date.
This won't help on the next update, but the following.  
I'll make sure to have it right before I push another update, and I'll keep you posted so you know when to make a backup.

**Comment by Gerschel** [comment]
I found the offending line of code in the webui. In modules/extensions.py, it does a hard reset.  

![image](https://user-images.githubusercontent.com/9631031/209453732-a03e1018-a87b-4f34-adc0-4ed788186021.png)

**Comment by Gerschel** [comment]
Should be resolved now. Your next pull will overwrite though, the logic will arive in that update. Be sure to make a backup first, update script will save the files that run, different than what the repository holds. 
`presets.json`, `additional_configs.json`.

**Comment by hzielke** [comment]
Great, works like a charm now!
